### ISSUE TITLE
Nothing named `snappy`

### ISSUE THREAD

**Issue by catb0t** [gokr/spry#8]
trying to build the ide, trying to run `tests/run.sh` and trying to run `nimble c tests/all` all complain like 

```
modules/sprycompress.nim(1, 8) Error: cannot open 'snappy'
  import snappy
         ^
```

`nimble install snappy` gives an error that the package is not found. where do i find the snappy package to make Spry build?

note this is also why travis-ci builds fail

**Comment by gokr** [comment]
I think if you first try `nimble build` in spry, it will install dependencies of which nimsnappy is listed. Otherwise `nimble search snappy` should find the **nimsnappy** package - which you install with `nimble install nimsnappy`. I switched to snappy deliberately because it was hard to get nimlz4 working :)

**Comment by catb0t** [comment]
Okay, that's solved *that* specific thing. Seems like you should add `nimsnappy` to the list of dependencies or something though :)
